[package]
name = "vcard"
version = "0.1.0"
authors = ["VyNT <vyngt@outlook.com>"]
keywords = ["vcard", "rfc6350"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vcard_derive = {path = "../vcard_derive"}